//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSTF.ToolkitHelpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonSTF.ToolkitHelpers.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no IDS to be fetched..
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range..
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is out of range..
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch: There are no values in the Fields collection..
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required..
        /// </summary>
        internal static string _205 {
            get {
                return ResourceManager.GetString("205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: Invalid project name..
        /// </summary>
        internal static string _206 {
            get {
                return ResourceManager.GetString("206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: Invalid User/Password..
        /// </summary>
        internal static string _207 {
            get {
                return ResourceManager.GetString("207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string _208 {
            get {
                return ResourceManager.GetString("208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch: ChannelViewer&apos;s Fields Type is incorrect..
        /// </summary>
        internal static string _209 {
            get {
                return ResourceManager.GetString("209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested ID(s) was invalid..
        /// </summary>
        internal static string _20a {
            get {
                return ResourceManager.GetString("20a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Error..
        /// </summary>
        internal static string _20b {
            get {
                return ResourceManager.GetString("20b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field type..
        /// </summary>
        internal static string _20c {
            get {
                return ResourceManager.GetString("20c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get selected ids: Project Window is not running per Tool Kit login values..
        /// </summary>
        internal static string _20d {
            get {
                return ResourceManager.GetString("20d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get selected ids: Project Window is not displaying the correct view..
        /// </summary>
        internal static string _20e {
            get {
                return ResourceManager.GetString("20e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project: Error launching application..
        /// </summary>
        internal static string _20f {
            get {
                return ResourceManager.GetString("20f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch: A SearchField name was not found in Fields..
        /// </summary>
        internal static string _210 {
            get {
                return ResourceManager.GetString("210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch: A SearchField condition was invalid.
        /// </summary>
        internal static string _211 {
            get {
                return ResourceManager.GetString("211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields Type can not be modified..
        /// </summary>
        internal static string _212 {
            get {
                return ResourceManager.GetString("212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolKit Option required to use this object..
        /// </summary>
        internal static string _213 {
            get {
                return ResourceManager.GetString("213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch requested method..
        /// </summary>
        internal static string _214 {
            get {
                return ResourceManager.GetString("214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is permanently locked..
        /// </summary>
        internal static string _215 {
            get {
                return ResourceManager.GetString("215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is currently being edited by another user..
        /// </summary>
        internal static string _216 {
            get {
                return ResourceManager.GetString("216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is too big..
        /// </summary>
        internal static string _217 {
            get {
                return ResourceManager.GetString("217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: SampleSetLines is empty..
        /// </summary>
        internal static string _218 {
            get {
                return ResourceManager.GetString("218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: SampleSetLine function property can not be 0..
        /// </summary>
        internal static string _219 {
            get {
                return ResourceManager.GetString("219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: SampleSetLine MethodSetOrReportMethod property must be set..
        /// </summary>
        internal static string _21a {
            get {
                return ResourceManager.GetString("21a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: May only be set for the first version of a method..
        /// </summary>
        internal static string _21b {
            get {
                return ResourceManager.GetString("21b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: SampleSetLine DataStart must be less than RunTime..
        /// </summary>
        internal static string _21c {
            get {
                return ResourceManager.GetString("21c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store (MoleWeights): A minimum of one molecular weight must be entered for a GPC Narrow Standard..
        /// </summary>
        internal static string _21d {
            get {
                return ResourceManager.GetString("21d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store (Moments): GPC Broad Standard average have been entered incorrectly. A minimum of 2 averages must be entered and average must be orderd such that: Mn &lt; Mv &lt; Mw &lt; Mz &lt; Mz+1..
        /// </summary>
        internal static string _21e {
            get {
                return ResourceManager.GetString("21e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: Duplicate Start values were found in the KAlpha table..
        /// </summary>
        internal static string _21f {
            get {
                return ResourceManager.GetString("21f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store (CumPercents): Can not have duplicate molecular weights..
        /// </summary>
        internal static string _220 {
            get {
                return ResourceManager.GetString("220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store (CumPercents): Can not have duplicate percents..
        /// </summary>
        internal static string _221 {
            get {
                return ResourceManager.GetString("221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store (CumPercents): At least two rows need to be entered..
        /// </summary>
        internal static string _222 {
            get {
                return ResourceManager.GetString("222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Connect: Already connected to the Instrument Server..
        /// </summary>
        internal static string _223 {
            get {
                return ResourceManager.GetString("223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Connect: Currently connecting to the Instrument Server..
        /// </summary>
        internal static string _224 {
            get {
                return ResourceManager.GetString("224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.Connect required..
        /// </summary>
        internal static string _225 {
            get {
                return ResourceManager.GetString("225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Failed to re-connect to Instrument Server..
        /// </summary>
        internal static string _226 {
            get {
                return ResourceManager.GetString("226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: invalid SampleSetLine..
        /// </summary>
        internal static string _227 {
            get {
                return ResourceManager.GetString("227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: No instrument matches found..
        /// </summary>
        internal static string _228 {
            get {
                return ResourceManager.GetString("228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Setup Instruments: invalid Instrument Method name..
        /// </summary>
        internal static string _229 {
            get {
                return ResourceManager.GetString("229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Error in Chromatographic System..
        /// </summary>
        internal static string _22a {
            get {
                return ResourceManager.GetString("22a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Processing Printer is required..
        /// </summary>
        internal static string _22b {
            get {
                return ResourceManager.GetString("22b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: can not connect to the Processing Server..
        /// </summary>
        internal static string _22c {
            get {
                return ResourceManager.GetString("22c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Processing Server Error..
        /// </summary>
        internal static string _22d {
            get {
                return ResourceManager.GetString("22d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Flow: A, B, C or D is invalid..
        /// </summary>
        internal static string _22e {
            get {
                return ResourceManager.GetString("22e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Flow: A + B + C + D must equal 100 Percent..
        /// </summary>
        internal static string _22f {
            get {
                return ResourceManager.GetString("22f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Flow: Invalid low/high pressure limit or low pressure limit is greater than the high pressure limit..
        /// </summary>
        internal static string _230 {
            get {
                return ResourceManager.GetString("230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Flow: Invalid ramp value..
        /// </summary>
        internal static string _231 {
            get {
                return ResourceManager.GetString("231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrom: Invalid Chromatogram type..
        /// </summary>
        internal static string _232 {
            get {
                return ResourceManager.GetString("232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrom: There are too may IDs to be fetched..
        /// </summary>
        internal static string _233 {
            get {
                return ResourceManager.GetString("233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrom: Cannot open file..
        /// </summary>
        internal static string _234 {
            get {
                return ResourceManager.GetString("234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Cannot Pause or Replace the Chromatographic System when it is executing SelectedLines..
        /// </summary>
        internal static string _235 {
            get {
                return ResourceManager.GetString("235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Rerun: Cannot modify entire SampleSetId - must use selected lines..
        /// </summary>
        internal static string _236 {
            get {
                return ResourceManager.GetString("236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Run / Rerun: selected line indices must be in sequential order..
        /// </summary>
        internal static string _237 {
            get {
                return ResourceManager.GetString("237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Chromatographic System must be idle to perform an injection..
        /// </summary>
        internal static string _238 {
            get {
                return ResourceManager.GetString("238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Inject / ReadyInject: The SampleSetLine&apos;s function value is not a valid injection function..
        /// </summary>
        internal static string _239 {
            get {
                return ResourceManager.GetString("239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Inject / ReadyInject: The SampleSetLine&apos;s numbe of injections must be one..
        /// </summary>
        internal static string _23a {
            get {
                return ResourceManager.GetString("23a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - Run / Rerun: Line number is not within the range of the sample set method..
        /// </summary>
        internal static string _23b {
            get {
                return ResourceManager.GetString("23b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument - RunWaitingSampleSet: The current job&apos;s system status must be &apos; wait for user&apos;..
        /// </summary>
        internal static string _23c {
            get {
                return ResourceManager.GetString("23c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: The Moments collection must either be empty or have a count of 6 Moment objects..
        /// </summary>
        internal static string _23d {
            get {
                return ResourceManager.GetString("23d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleSetMethod - Store: The Moments collection items must be order by Moment.Moment equaling Mn, Mw, Mz, Mz+1, Mv, and MP in that order..
        /// </summary>
        internal static string _23e {
            get {
                return ResourceManager.GetString("23e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Chromatographic Systems with multiple pumps not supported..
        /// </summary>
        internal static string _23f {
            get {
                return ResourceManager.GetString("23f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive - There was a serialization error during a read/write to the archive, see message center for details..
        /// </summary>
        internal static string _240 {
            get {
                return ResourceManager.GetString("240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive - Attempt to collect unknown type.
        /// </summary>
        internal static string _241 {
            get {
                return ResourceManager.GetString("241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive - Error opening archive file.
        /// </summary>
        internal static string _242 {
            get {
                return ResourceManager.GetString("242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The Project name contains invalid characters!.
        /// </summary>
        internal static string _243 {
            get {
                return ResourceManager.GetString("243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The length of the Project name is too long - See Message Board for more information..
        /// </summary>
        internal static string _244 {
            get {
                return ResourceManager.GetString("244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The name is already used by another Project on this database..
        /// </summary>
        internal static string _245 {
            get {
                return ResourceManager.GetString("245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The Project name must start with a letter..
        /// </summary>
        internal static string _246 {
            get {
                return ResourceManager.GetString("246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The User Type is not valid on this database..
        /// </summary>
        internal static string _247 {
            get {
                return ResourceManager.GetString("247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - An internal error has occurred while obtaining the project names..
        /// </summary>
        internal static string _248 {
            get {
                return ResourceManager.GetString("248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The Comments cannot be empty when Full Audit Trail is enabled..
        /// </summary>
        internal static string _249 {
            get {
                return ResourceManager.GetString("249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The source Project specified is not a valid source Project for this operation..
        /// </summary>
        internal static string _24a {
            get {
                return ResourceManager.GetString("24a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - A unique name must be provided before the Project can be created..
        /// </summary>
        internal static string _24b {
            get {
                return ResourceManager.GetString("24b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - An unknown error has occurred while creating the project - See Message Board for more information..
        /// </summary>
        internal static string _24c {
            get {
                return ResourceManager.GetString("24c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The Group or World access type must be a valid user type or is empty..
        /// </summary>
        internal static string _24d {
            get {
                return ResourceManager.GetString("24d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - An internal error has occurred while obtaining the members of the Group - See Message Board for more information..
        /// </summary>
        internal static string _24e {
            get {
                return ResourceManager.GetString("24e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - User does not have the privilege to perform this action on the Group - See Message Board for more information..
        /// </summary>
        internal static string _24f {
            get {
                return ResourceManager.GetString("24f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group could not be removed - See Message Board for more information..
        /// </summary>
        internal static string _250 {
            get {
                return ResourceManager.GetString("250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group could not be renamed - See Message Board for more information..
        /// </summary>
        internal static string _251 {
            get {
                return ResourceManager.GetString("251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - User could not be added to the Group, or is already a member - See Message Board for more information..
        /// </summary>
        internal static string _252 {
            get {
                return ResourceManager.GetString("252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - User could not be removed from the Group - See Message Board for more information..
        /// </summary>
        internal static string _253 {
            get {
                return ResourceManager.GetString("253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - User cannot be removed because they are not a member of the Group - See Message Board for more information..
        /// </summary>
        internal static string _254 {
            get {
                return ResourceManager.GetString("254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group cannot be renamed because the new name is already in use by another Group - See Message Board for more information..
        /// </summary>
        internal static string _255 {
            get {
                return ResourceManager.GetString("255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - User does not exist on this database - See Message Board for more information..
        /// </summary>
        internal static string _256 {
            get {
                return ResourceManager.GetString("256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group does not exists on this database - See Message Board for more information..
        /// </summary>
        internal static string _257 {
            get {
                return ResourceManager.GetString("257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group already exists on this database - See Message Board for more information..
        /// </summary>
        internal static string _258 {
            get {
                return ResourceManager.GetString("258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup - The User Group could not be created - See Message Board for more information..
        /// </summary>
        internal static string _259 {
            get {
                return ResourceManager.GetString("259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the name is too long - See Message Board for more information..
        /// </summary>
        internal static string _25e {
            get {
                return ResourceManager.GetString("25e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name provided is not a valid name for a User, UserType, or UserGroup..
        /// </summary>
        internal static string _25f {
            get {
                return ResourceManager.GetString("25f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have sufficient privileges for this operation..
        /// </summary>
        internal static string _260 {
            get {
                return ResourceManager.GetString("260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive - The file currently exists and the Replace flag is set to &quot;False&quot;.
        /// </summary>
        internal static string _261 {
            get {
                return ResourceManager.GetString("261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - This field cannot be changed unless Full Audit Trail is enabled..
        /// </summary>
        internal static string _262 {
            get {
                return ResourceManager.GetString("262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive - Attempt to write objects to archive file opened for read, or read objects from archive file opened for write..
        /// </summary>
        internal static string _263 {
            get {
                return ResourceManager.GetString("263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstrumentMethod - Store: InstSetups collection is empty..
        /// </summary>
        internal static string _264 {
            get {
                return ResourceManager.GetString("264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An option is required to open this method. Please make sure this option is enabled in the project - See Message Board for more information..
        /// </summary>
        internal static string _267 {
            get {
                return ResourceManager.GetString("267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: User has been disabled..
        /// </summary>
        internal static string _26d {
            get {
                return ResourceManager.GetString("26d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: User has been removed..
        /// </summary>
        internal static string _26e {
            get {
                return ResourceManager.GetString("26e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: User does not exist..
        /// </summary>
        internal static string _26f {
            get {
                return ResourceManager.GetString("26f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject - The project path name must be one of the paths returned by the ProjectPathNames property.
        /// </summary>
        internal static string _270 {
            get {
                return ResourceManager.GetString("270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already in use - See Message Board for more information..
        /// </summary>
        internal static string _271 {
            get {
                return ResourceManager.GetString("271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be between 4 and 30 characters..
        /// </summary>
        internal static string _272 {
            get {
                return ResourceManager.GetString("272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has expired..
        /// </summary>
        internal static string _275 {
            get {
                return ResourceManager.GetString("275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebService Enabled - ThisToolkit Function is not avaliable.
        /// </summary>
        internal static string _276 {
            get {
                return ResourceManager.GetString("276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - Login: User password is below the minimum required length as set by the System Policies. Please log in directly to enter a new password..
        /// </summary>
        internal static string _277 {
            get {
                return ResourceManager.GetString("277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - LaunchMilApp: Unsupported User Interface.
        /// </summary>
        internal static string _278 {
            get {
                return ResourceManager.GetString("278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Package Option has not been installed yet. Please install the option and try again..
        /// </summary>
        internal static string _279 {
            get {
                return ResourceManager.GetString("279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error exporting system audit trail.
        /// </summary>
        internal static string _27a {
            get {
                return ResourceManager.GetString("27a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: A Backup/Restore operation is currently in progress..
        /// </summary>
        internal static string _27b {
            get {
                return ResourceManager.GetString("27b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Cannot connect to Millennium database.
        /// </summary>
        internal static string _27e {
            get {
                return ResourceManager.GetString("27e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Could not find schema for project name supplied.
        /// </summary>
        internal static string _27f {
            get {
                return ResourceManager.GetString("27f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error opening INF file.
        /// </summary>
        internal static string _281 {
            get {
                return ResourceManager.GetString("281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error opening the .INF file.
        /// </summary>
        internal static string _286 {
            get {
                return ResourceManager.GetString("286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Project already exists.
        /// </summary>
        internal static string _287 {
            get {
                return ResourceManager.GetString("287", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: The project name supplied is illegal.
        /// </summary>
        internal static string _288 {
            get {
                return ResourceManager.GetString("288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: This project is currently in use.
        /// </summary>
        internal static string _289 {
            get {
                return ResourceManager.GetString("289", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error deleting project files.
        /// </summary>
        internal static string _28a {
            get {
                return ResourceManager.GetString("28a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error deleting project.
        /// </summary>
        internal static string _28b {
            get {
                return ResourceManager.GetString("28b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolKit: Comments are required for this operation.
        /// </summary>
        internal static string _28c {
            get {
                return ResourceManager.GetString("28c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - LoginY: Invalid Security Token.
        /// </summary>
        internal static string _28d {
            get {
                return ResourceManager.GetString("28d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project - LoginY: The create date provided does not match database entry for this project.
        /// </summary>
        internal static string _28e {
            get {
                return ResourceManager.GetString("28e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified User Type is not a valid type for the User name supplied.
        /// </summary>
        internal static string _292 {
            get {
                return ResourceManager.GetString("292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TkArchive: Error exporting JCAMP file.
        /// </summary>
        internal static string _296 {
            get {
                return ResourceManager.GetString("296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProject: Error deleting project, project has descendents.
        /// </summary>
        internal static string _299 {
            get {
                return ResourceManager.GetString("299", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBProject: Failed to set SDMS State.
        /// </summary>
        internal static string _29e {
            get {
                return ResourceManager.GetString("29e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - Notify Enable: Not connected to Processing Server..
        /// </summary>
        internal static string _300 {
            get {
                return ResourceManager.GetString("300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - NotifyEnable: Error attempting to clear notification..
        /// </summary>
        internal static string _301 {
            get {
                return ResourceManager.GetString("301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - NotifyEnable: At least one event notification property must be set..
        /// </summary>
        internal static string _302 {
            get {
                return ResourceManager.GetString("302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - NotifyEnable: Error attempting to set notification..
        /// </summary>
        internal static string _303 {
            get {
                return ResourceManager.GetString("303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - Connect: Could not connect to Processing Server..
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control: Connect: Already connected..
        /// </summary>
        internal static string _305 {
            get {
                return ResourceManager.GetString("305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - Must be within a control&apos;s event handler to call this function..
        /// </summary>
        internal static string _306 {
            get {
                return ResourceManager.GetString("306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - Continue: Processing Server error..
        /// </summary>
        internal static string _307 {
            get {
                return ResourceManager.GetString("307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - NotifyEnable: The Processing Server already enabled for event notification..
        /// </summary>
        internal static string _308 {
            get {
                return ResourceManager.GetString("308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Control - Continue: Could not update the result data in the Processing Server..
        /// </summary>
        internal static string _309 {
            get {
                return ResourceManager.GetString("309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit Login required..
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Toolkit option is required to use this object. Please verify that the option is enabled for this project..
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : you must set the Name property before calling Fetch..
        /// </summary>
        internal static string _406 {
            get {
                return ResourceManager.GetString("406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method could not be opened in the Project - See Message Board for more information..
        /// </summary>
        internal static string _408 {
            get {
                return ResourceManager.GetString("408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call the Fetch method before accessing this property..
        /// </summary>
        internal static string _409 {
            get {
                return ResourceManager.GetString("409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set Line : object has not be initialized within the collection..
        /// </summary>
        internal static string _40a {
            get {
                return ResourceManager.GetString("40a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name is not a valid name, or is empty..
        /// </summary>
        internal static string _40b {
            get {
                return ResourceManager.GetString("40b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index is not within a valid range.
        /// </summary>
        internal static string _40c {
            get {
                return ResourceManager.GetString("40c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method : you must set the Name property before calling Fetch..
        /// </summary>
        internal static string _40d {
            get {
                return ResourceManager.GetString("40d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open Method because it is being edited by another user..
        /// </summary>
        internal static string _40e {
            get {
                return ResourceManager.GetString("40e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : cannot be saved because it has been permanently locked from change. Must set name property to a new name..
        /// </summary>
        internal static string _40f {
            get {
                return ResourceManager.GetString("40f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : cannot be saved because its size is too large..
        /// </summary>
        internal static string _410 {
            get {
                return ResourceManager.GetString("410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : instrument method specified does not exist in this project..
        /// </summary>
        internal static string _411 {
            get {
                return ResourceManager.GetString("411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : processing method specified does not exist in this project..
        /// </summary>
        internal static string _412 {
            get {
                return ResourceManager.GetString("412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : report method specified does not exist in this project..
        /// </summary>
        internal static string _413 {
            get {
                return ResourceManager.GetString("413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : export method specified does not exist in this project..
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Copy : source project and destination project must be different!.
        /// </summary>
        internal static string _415 {
            get {
                return ResourceManager.GetString("415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Copy : the method in the destination project is permanently locked and cannot be overwritten..
        /// </summary>
        internal static string _416 {
            get {
                return ResourceManager.GetString("416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified failure has occurred while saving the method to the databse..
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Copy : could not be copied to the destination project because an existing method with the same name and type is present and cannot be over written..
        /// </summary>
        internal static string _418 {
            get {
                return ResourceManager.GetString("418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : you must set the Name property of the object before calling Fetch..
        /// </summary>
        internal static string _419 {
            get {
                return ResourceManager.GetString("419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method : this method can not be removed..
        /// </summary>
        internal static string _41a {
            get {
                return ResourceManager.GetString("41a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : ProcMthComponents collection failed to initialize properly..
        /// </summary>
        internal static string _41b {
            get {
                return ResourceManager.GetString("41b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : NameGroups collection failed to initialize properly..
        /// </summary>
        internal static string _41c {
            get {
                return ResourceManager.GetString("41c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : TimeGroups collection failed to initialize properly..
        /// </summary>
        internal static string _41d {
            get {
                return ResourceManager.GetString("41d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : SysSuitParameters object failed to initialize properly..
        /// </summary>
        internal static string _41e {
            get {
                return ResourceManager.GetString("41e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuitabilityLimit : unable to retrieve the field name..
        /// </summary>
        internal static string _41f {
            get {
                return ResourceManager.GetString("41f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : cannot open a GPC processing method using this object..
        /// </summary>
        internal static string _420 {
            get {
                return ResourceManager.GetString("420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Set : MethodSetLines collection failed to initialize properly..
        /// </summary>
        internal static string _421 {
            get {
                return ResourceManager.GetString("421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : ProcMthComponents collection failed to initialize properly..
        /// </summary>
        internal static string _422 {
            get {
                return ResourceManager.GetString("422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object only supports getting property values not setting properties!.
        /// </summary>
        internal static string _423 {
            get {
                return ResourceManager.GetString("423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod : IntegrationParameters failed to initialize properly..
        /// </summary>
        internal static string _424 {
            get {
                return ResourceManager.GetString("424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodSetLine the channel name is not a valid - See Message Board for more information..
        /// </summary>
        internal static string _425 {
            get {
                return ResourceManager.GetString("425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodSetLine the processing method name does not exist in this project - See Message Board for more information..
        /// </summary>
        internal static string _426 {
            get {
                return ResourceManager.GetString("426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodSetLine the reporting method name does not exist in this project - See Message Board for more information..
        /// </summary>
        internal static string _427 {
            get {
                return ResourceManager.GetString("427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection : the value is not within a valid range..
        /// </summary>
        internal static string _428 {
            get {
                return ResourceManager.GetString("428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCalibration : the requested calibration could not be fetched..
        /// </summary>
        internal static string _429 {
            get {
                return ResourceManager.GetString("429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCalibration : the requested calibration type is GPC. This calibration type is not compatible with this object..
        /// </summary>
        internal static string _42a {
            get {
                return ResourceManager.GetString("42a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCalibration : LCCalCurves collection failed to initialize properly..
        /// </summary>
        internal static string _42b {
            get {
                return ResourceManager.GetString("42b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCalCurve : LCCalPoints collection failed to initialize properly..
        /// </summary>
        internal static string _42c {
            get {
                return ResourceManager.GetString("42c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCCalCurve : AvgCalPoints collection failed to initialize properly..
        /// </summary>
        internal static string _42d {
            get {
                return ResourceManager.GetString("42d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An option is required to open this method. Please make sure the the option is enabled in the project - See Message Board for more information..
        /// </summary>
        internal static string _42e {
            get {
                return ResourceManager.GetString("42e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An option is required in order to access this interface. Please make sure that the option is turned on in the project - See Message Board for more information..
        /// </summary>
        internal static string _42f {
            get {
                return ResourceManager.GetString("42f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportMethod : The directory &lt;Xxx&gt; for the export file does not exist, or is empty!.
        /// </summary>
        internal static string _430 {
            get {
                return ResourceManager.GetString("430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportMethod : The root filename cannot be a zero length string..
        /// </summary>
        internal static string _431 {
            get {
                return ResourceManager.GetString("431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string exceeds the maximum number of characters for this property!.
        /// </summary>
        internal static string _432 {
            get {
                return ResourceManager.GetString("432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportMethod : The FileRoot property contains invalid characters!.
        /// </summary>
        internal static string _433 {
            get {
                return ResourceManager.GetString("433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reporting method does not exist in this project..
        /// </summary>
        internal static string _434 {
            get {
                return ResourceManager.GetString("434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest unable to connect to the processing server on the computer - See Message Board for more information..
        /// </summary>
        internal static string _435 {
            get {
                return ResourceManager.GetString("435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest unable to obtain the processing printers on the computer - See Message Board for more information..
        /// </summary>
        internal static string _436 {
            get {
                return ResourceManager.GetString("436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : a failure occurred while running the request on the processing server..
        /// </summary>
        internal static string _437 {
            get {
                return ResourceManager.GetString("437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : incomplete processing information to run the request..
        /// </summary>
        internal static string _438 {
            get {
                return ResourceManager.GetString("438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : incomplete reporting information to run the request..
        /// </summary>
        internal static string _439 {
            get {
                return ResourceManager.GetString("439", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : incomplete exporting information to run the request..
        /// </summary>
        internal static string _43a {
            get {
                return ResourceManager.GetString("43a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : the Ids collection is empty..
        /// </summary>
        internal static string _43b {
            get {
                return ResourceManager.GetString("43b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessingRequest : a failure occurred while fetching the registered nodes from the database..
        /// </summary>
        internal static string _43c {
            get {
                return ResourceManager.GetString("43c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlterSample : the Id property is not valid, or this Injection Id doesn&apos;t exist in this project..
        /// </summary>
        internal static string _43d {
            get {
                return ResourceManager.GetString("43d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlterSample : the Injection could not be fetched from the project..
        /// </summary>
        internal static string _43e {
            get {
                return ResourceManager.GetString("43e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlterSample : this property is read-only. You cannot assign it a new value..
        /// </summary>
        internal static string _43f {
            get {
                return ResourceManager.GetString("43f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlterSample : an error occurred while attempting to update this sample in the database..
        /// </summary>
        internal static string _440 {
            get {
                return ResourceManager.GetString("440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlterSample : you must call Fetch() first before calling this method or property..
        /// </summary>
        internal static string _441 {
            get {
                return ResourceManager.GetString("441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod: ProcMthComponents collection failed to serialize properly..
        /// </summary>
        internal static string _442 {
            get {
                return ResourceManager.GetString("442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod: TimeGroups collection failed to serialize properly..
        /// </summary>
        internal static string _443 {
            get {
                return ResourceManager.GetString("443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod: NameGroups collection failed to serialize properly..
        /// </summary>
        internal static string _444 {
            get {
                return ResourceManager.GetString("444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod: SystemSuitability object failed to serialize properly..
        /// </summary>
        internal static string _445 {
            get {
                return ResourceManager.GetString("445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCProcMethod: IntegrationParameters object failed to serialize properly..
        /// </summary>
        internal static string _446 {
            get {
                return ResourceManager.GetString("446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Copy : can&apos;t copy from non-FAT projects into FAT projects. Please check the system policies..
        /// </summary>
        internal static string _447 {
            get {
                return ResourceManager.GetString("447", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unregister the Millennium Toolkit Extension type library!.
        /// </summary>
        internal static string _448 {
            get {
                return ResourceManager.GetString("448", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegSvr32 Error.
        /// </summary>
        internal static string _449 {
            get {
                return ResourceManager.GetString("449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolKit: Comments are required for this operation.
        /// </summary>
        internal static string _44a {
            get {
                return ResourceManager.GetString("44a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtocolMethod: Duplicate test line description found, Every test line descriptions must be unique..
        /// </summary>
        internal static string _44b {
            get {
                return ResourceManager.GetString("44b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtocolTestLine: The selected test line already has data attached and therefore cannot be changed to a different test..
        /// </summary>
        internal static string _44c {
            get {
                return ResourceManager.GetString("44c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtocolMethod: This method has already been approved so no changes can be saved to it..
        /// </summary>
        internal static string _44d {
            get {
                return ResourceManager.GetString("44d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument: Nodes Property Report cannot be retrieved.
        /// </summary>
        internal static string _44e {
            get {
                return ResourceManager.GetString("44e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBProject: The project does not exist in the database - See Message Board for more information..
        /// </summary>
        internal static string _44f {
            get {
                return ResourceManager.GetString("44f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBProject: User does not have sufficient privilege to perform the requested action on project or sub-project, therefore can not operate on this project or any of its sub-projects - See Message Board for more information..
        /// </summary>
        internal static string _450 {
            get {
                return ResourceManager.GetString("450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: Cannot delete permanent user - See Message Board for more information..
        /// </summary>
        internal static string _451 {
            get {
                return ResourceManager.GetString("451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBProject: The requested action can not be performed on project because the project is in use (files being moved, etc.) or locked - See Message Board for more information..
        /// </summary>
        internal static string _452 {
            get {
                return ResourceManager.GetString("452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBProject: Unable to set lock on the project - See Message Board for more information..
        /// </summary>
        internal static string _453 {
            get {
                return ResourceManager.GetString("453", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User revalidation is required to complete this task..
        /// </summary>
        internal static string _454 {
            get {
                return ResourceManager.GetString("454", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebService Enabled - ThisToolkit Function is not avaliable.
        /// </summary>
        internal static string _455 {
            get {
                return ResourceManager.GetString("455", resourceCulture);
            }
        }
    }
}
